### ISSUE TITLE
Splash screen is annoying

### ISSUE THREAD

**Issue by jayschwa** [laanwj/bitcoin-qt#13]
The opening splash screen (picture of a bitcoin wallet with text explaining "boot" status along the bottom) is annoying. It was on my screen for a minute or two while it loaded blocks. This is too long and it obscured my vision of other windows (since it appears to always be on top). I think it would be better if this was converted to explicit window so it can be hidden or moved around while it loads.

**Comment by laanwj** [comment]
Can you try changing this line? (bitcoin.cpp, line 123)

```
QSplashScreen splash(QPixmap(":/images/splash"),
```

Qt::WindowStaysOnTopHint);

Maybe there is some combination of flags that it still works as a splash
screen but is less annoying...

**Comment by laanwj** [comment]
Changing the flag to 0 seems to mitigate the "annoying behaviour". Can you
check?

**Comment by danpalmer** [comment]
I can confirm, this fix works for me too.

**Comment by graingert** [comment]
Sadly this doesn't fix the issue for me, try another random value

**Comment by laanwj** [comment]
@graingert: be sure to use a cryptographically sound random number generation, preferably one based on quantum decoherence. If you find any useful random numbers, do let us know.

@rest: committed
