### ISSUE TITLE
Encryption?

### ISSUE THREAD

**Issue by msva** [laanwj/bitcoin-qt#18]
It is "wallet encryption" section in upstream's readme, that tell us, that it is possible to encrypt wallet.dat (and set up a password for it) in they's client (btw, i can't find it even in wx interface) by clicking Encrypt Wallet item in menu.
did you plannig to add some similar function?
Or working with GPG :D.

**Comment by laanwj** [comment]
Yes, I plan to add this to the ui, it indeed is already in upstream
Op 14 aug. 2011 06:12 schreef "msva" <
reply@reply.github.com>
het volgende:

**Comment by laanwj** [comment]
This has been implemented
