### ISSUE TITLE
Bug in hint for synchronization status

### ISSUE THREAD

**Issue by msva** [laanwj/bitcoin-qt#19]
If current block index is up to date hint shows:
«...last recieve block was generated %n second(s) ago.»
May be it'll be better to pass at least "0" (or remember last generation time and update elapsed time on every hint showing) to this?

**Comment by laanwj** [comment]
When does this happen? I have been unable to reproduce this; here, it shows
a value in place of "%n". For example "last recieve block was generated 60
second(s) ago"

**Comment by msva** [comment]
i've catch this once, after long time of working with wallet. Possibly, it appears after running with already synchronized wallet, but, as I said, i've catch it only once for now. I'll try to catch it once more when I fix laptop or by a new one ;)

**Comment by laanwj** [comment]
Ok, please re-open this issue when you're able to reproduce it.
