### ISSUE TITLE
More Mac-like

### ISSUE THREAD

**Issue by p2k** [laanwj/bitcoin-qt#27]
On a Mac, some rules of GUI programming are different. Besides some minor cosmetic things, a crucial part is the Dock vs. Tray vs. Taskbar understanding.

On a Mac, there is no Taskbar in the traditional sence. Instead there is the so-called Dock at the bottom of the screen. It behaves like a mixture of Taskbar and Tray. There is only one icon per application, not per window. Right-clicking the dock icon will reveal a menu which can be configured. The dock icon can be clicked and that click can be interpreted by the application.

So far so good, but the Mac also has a second concept of a Tray, which (unfortunately?) gets mapped by Qt's QSystemTrayIcon. That Tray is at the upper right of the Mac's global menu bar and is intended for applications which mostly don't have any windows and don't appear at the dock (background services like Dropbox for example).

In Bitcoin-Qt (which is more of a foreground application) we have both, the Dock icon and the Tray icon which basically provide the exact same functionality. So what I would suggest is to remove the Tray icon on Mac and instead move its functionality completely to the Dock icon which feels more "right" for Mac users. That would also obsolete some options in the settings menu. This can all be achieved by conditional compiling (#ifdef Q_WS_MAC) and I got everything ready to do that, I'm just waiting for your OK.

**Comment by laanwj** [comment]
I cannot really judge this as I don't work with MacOSX myself. But it sounds like a good idea to make it more native to the platform.  

If you're going to implement this, please do try to abstract away as much as possible of the platform-specific functionality (as I did with the Notificator for DBUS).

**Comment by laanwj** [comment]
Let's close this issue, we have the pull request now.
