### ISSUE TITLE
View in transaction list doesn't use theme text color

### ISSUE THREAD

**Issue by tylendel** [laanwj/bitcoin-qt#3]
I use a dark theme to keep the eye cancer at bay :)  The transaction list however still seems to want to use black text, which can't be seen with a dark theme.  Is there any way to change that text?  Or get it to use the colors set in qtconfig?

**Comment by laanwj** [comment]
Ah, you're right. Seems that I force it to use black,

transactiontablemodel.cpp:

```
    /* Non-confirmed transactions are grey */
    if(rec->status.confirmed)
    {
        return QColor(0, 0, 0);
    }
    else
    {
        return QColor(128, 128, 128);
    }
```

I've now updated this now to return the default in case of a confirmed
transaction, which should fix it. Please update.

BTW do you know a nice dark Qt theme to test with?

**Comment by tylendel** [comment]
Honestly no, not a direct QT theme.  This is a dark gtk theme which uses qtconfig's ability to also match itself to the gtk theme.  http://gnome-look.org/content/show.php/Elegant+Dark+?content=136556

**Comment by tylendel** [comment]
Updated and it looks great, thanks very much for all the work :)  Someday I'll be able to post on the forums, still new and limited to the newbie section :)
