### ISSUE TITLE
Not sure if this is an issue specific to bitcoin-qt

### ISSUE THREAD

**Issue by tylendel** [laanwj/bitcoin-qt#4]
It seems to be just randomly creating new addresses now and again, which is filling up the address list with new addresses I didn't ask for.  Seems to happen on startup, but i'm not 100% sure.  I will keep an eye on it to see if I can figure out when it's happening.  Is this something that original bitcoin does?  Or is it something bitcoin-qt does?

**Comment by laanwj** [comment]
Unless there is a bug, this is not specific to bitcoin-qt. The GUI only
creates new addresses when you ask for it.

I think what happens in your case is that the core creates a new address
every time that it receives coins on the default address. See AddToWallet in
src/main.cpp:

```
    // If default receiving address gets used, replace it with a new one
    CScript scriptDefaultKey;
    scriptDefaultKey.SetBitcoinAddress(vchDefaultKey);
    BOOST_FOREACH(const CTxOut& txout, wtx.vout)
    {
        if (txout.scriptPubKey == scriptDefaultKey)
        {
            CWalletDB walletdb;
            vchDefaultKey = GetKeyFromKeyPool();
            walletdb.WriteDefaultKey(vchDefaultKey);
            walletdb.WriteName(PubKeyToAddress(vchDefaultKey), "");
        }
    }
```

**Comment by tylendel** [comment]
yeah, that would be it.  _sigh_ be nice if the nannying wasn't there.  sheesh.

**Comment by laanwj** [comment]
maybe it should be an option?

**Comment by tylendel** [comment]
for sure.  I am all about option overload with a sensible default.
