### ISSUE TITLE
Change Your Receiving Address is not working

### ISSUE THREAD

**Issue by bdheeman** [laanwj/bitcoin-qt#6]
Changing your receiving address is not working; the an Address Book dialog appears, but selecting any address from the table view does not make it a default receiving address.

**Comment by laanwj** [comment]
Confirmed. There is currently no way to change the default receiving address
beyond creating a new one using the button in the main window.

I'll put it on my TODO list.

**Comment by laanwj** [comment]
Should be fixed now. You can set an address as default by editing it in the address book and checking "Set as default address" or creating a new address and checking that checkbox.
